# Generated by Django 5.2.13 on 2026-05-08 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bk_tree_manager', '0002_word_wordurl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordurl',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_url', to='bk_tree_manager.word'),
        ),
    ]
