# Generated by Django 5.2.14 on 2026-05-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bk_tree_manager', '0003_alter_wordurl_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='priority',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
    ]
