# Generated by Django 5.2.14 on 2026-05-12 04:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_name', models.CharField(max_length=255)),
                ('db_host', models.CharField(max_length=255)),
                ('db_user', models.CharField(max_length=255)),
                ('db_password', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('tables', models.JSONField(default=list)),
                ('prompt', models.TextField()),
                ('queries', models.JSONField(default=list)),
                ('db_type', models.CharField(choices=[('mysql', 'MySQL DB'), ('postgres', 'PostgresQL DB')], max_length=255)),
                ('constraints', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None)),
            ],
        ),
    ]
